services:
  web:
    build: .
    container_name: social-media-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - social-media-media:/app/media
      - social-media-static:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: social-media-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - social-media-static:/app/staticfiles:ro
      - social-media-media:/app/media:ro
    depends_on:
      - web

volumes:
  social-media-media:
  social-media-static: