# Generated by Django 5.0 on 2025-10-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.post'),
        ),
    ]
